### ISSUE TITLE
Warning when opening .pptx

### ISSUE THREAD

**Issue by iuliancioarca** [ASML-Labs/PPTX.jl#21]
I followed the documentation tutorial and got the following warning when opening the resulting file: 
![image](https://user-images.githubusercontent.com/10220105/217872236-c614cd5e-2160-43a5-873e-9ca1bf35268a.png)
![image](https://user-images.githubusercontent.com/10220105/217871080-7a4adb94-53ee-4529-8418-2cbf92d67359.png)

The presentation opens and looks ok. I don't know what "content was removed".
Tested on Windows 10 with Office 2019.

**Comment by matthijscox-asml** [comment]
I also noticed this on some alternative templates. As long as nothing is removed, it should be fine. 
It would be nice to find the root cause at some point, but I do not consider this a critical issue.
