### ISSUE TITLE
Slow precompilation of PPTX

### ISSUE THREAD

**Issue by matthijscox-asml** [ASML-Labs/PPTX.jl#25]
I don't know if others have noticed, but I am noticing slow precompile times. It can take 1-2 minutes some times. I am currently on Julia 1.8.5. 

Would be nice if someone can do a quick investigation. I'd like to know if this is due to some poor coding pattern in PPTX.jl or it is just due to a dependency.

**Comment by jaakkor2** [comment]
Replacing `using Images` in https://github.com/ASML-Labs/PPTX.jl/blob/v0.5.3/src/Picture.jl#L1 with `using FileIO, ImageIO` (and corresponding deps in `Project.toml`) speeds ups usage considerably

PPTX.jl 0.5.3
```
julia> @time using PPTX
  3.238382 seconds (4.79 M allocations: 301.566 MiB, 5.46% gc time, 6.04% compilation time: 12% of which was recompilation)
```
to
```
julia> @time using PPTX
  0.367717 seconds (397.38 k allocations: 24.847 MiB, 5.94% gc time, 12.91% compilation time)
```

**Comment by matthijscox-asml** [comment]
Oh, nice, thanks for checking that!
Do you happen to have time to make a PR? :)

**Comment by matthijscox-asml** [comment]
This seems tackled now in 0.6.0
