### ISSUE TITLE
add picture with .wmf , .emf format will result corrupted pptx file while opening with M$office

### ISSUE THREAD

**Issue by testercwt** [ASML-Labs/PPTX.jl#28]
Picture("xxx.wmf") can be added to Presentation . But when opend the output file , it showed corrupted file message

**Comment by matthijscox-asml** [comment]
After you've pressed the "repair" button, can you still see the pptx presentation? If yes, does the repaired presentation still show the picture? Or is the picture removed by the repair?

**Comment by testercwt** [comment]
> After you've pressed the "repair" button, can you still see the pptx presentation? If yes, does the repaired presentation still show the picture? Or is the picture removed by the repair?

yes, still show the picture

**Comment by BigBugBuzz** [comment]
What was the solution to this issue? I still encounter it.

`p = plot(df.CMAsk)
savefig(p, art_data_directory * "my_plot.svg")
my_plot = Picture(art_data_directory * "my_plot.png", offset_x=100, offset_y=100)
push!(s3, my_plot)

push!(pres, s3)

pres

PPTX.write(directory * filename, pres, overwrite = true, open_ppt=false)`

![Error](https://github.com/ASML-Labs/PPTX.jl/assets/161761325/804f4b6d-468a-420c-8e9a-017f016788d1)
