### ISSUE TITLE
Tables with colors

### ISSUE THREAD

**Issue by matthijscox-asml** [ASML-Labs/PPTX.jl#41]
> Note: this is mostly a brainstorm with myself.

I recently saw many colleagues automatically create tables with colors from scripts. 

For example, coloring the background of a table element red or green based the value of a number in the table element. Managers love those kind of quick overviews. And of course change the font color (at least to black or white depending on the background color).

Stuff such as this:

![image](https://github.com/ASML-Labs/PPTX.jl/assets/79519355/c08473e4-ebac-49cc-ade6-59c3da2507ba)

There's all these other configurations, like border colors. But let's start with something simple, such as the background color.

Main trouble is how to make this a bit user friendly. My only guess right now would be to make a table/dataframe/matrix object where the elements are not just strings, but TextBox, or TableElement types or something, with lots of properties that you can change. That would give full flexibility per table element at least. 

(May have to combine this with easier TextBox/TextBody configuration, font/alignment/etc. Maybe consider to use the same API as [Makie.Text](https://docs.makie.org/stable/examples/plotting_functions/text/index.html#text)?)

(We could also add like a formatter function to the PPTX.Table, to style each element based on the content, see PrettyTables.jl for example. Maybe Term.jl has some good ideas as well.)

**Comment by jaakkor2** [comment]
What if PrettyTables.jl had an XML backend ..

**Comment by matthijscox-asml** [comment]
> What if PrettyTables.jl had an XML backend ..

Interesting idea :) But actually it would be a PPTX backend, because there is no standard way to define a table in XML. 
So I wonder if there would be any benefit to add that code to PrettyTables.jl instead of here.

**Comment by matthijscox-asml** [comment]
v0.10.0 has these features, I added an example to the docs on how to generate the table in the original post.
