### ISSUE TITLE
Fixing the repair action on missing content types

### ISSUE THREAD

**Issue by matthijscox-asml** [ASML-Labs/PPTX.jl#45]
In v0.6.4 and v0.6.5 we (@jaakkor2 and me) tried to fix the PowerPoint repair action for missing content types in [ContentTypes].xml, such as svg etc.

Previous issues and PR's with discussion:
* https://github.com/ASML-Labs/PPTX.jl/issues/32
* https://github.com/ASML-Labs/PPTX.jl/pull/42
* https://github.com/ASML-Labs/PPTX.jl/pull/43

In summary, with this this code:
https://github.com/ASML-Labs/PPTX.jl/blob/1a63efb6ddd5de9439fdc50ec8d40fd5722d67d0/src/write.jl#L71-L94

Called in `PPTX.write` here:
https://github.com/ASML-Labs/PPTX.jl/blob/1a63efb6ddd5de9439fdc50ec8d40fd5722d67d0/src/write.jl#L186

We get succeeding CI. But when installing the package via Pkg we get an error:
```
ERROR: SystemError: opening file "C:\\Users\\matcox\\AppData\\Local\\Temp\\jl_P7kDYd\\no-slides\\[Content_Types].xml": Permission denied
```

**Comment by matthijscox-asml** [comment]
At least I found a way to troubleshoot without registering a new package version in the Registry. We can push to main and install the package via Pkg, and then I reproduced the problem.

Install the main branch via Pkg:
```julia
pkg>add https://github.com/ASML-Labs/PPTX.jl.git
```

Or maybe we can even do this already on the branch, according to [Pkg docs](https://pkgdocs.julialang.org/v1/managing-packages/)
```julia
pkg>add PPTX#my-branch
```

**Comment by jaakkor2** [comment]
I can `stat(path)`, and `read(path)`, but `readxml(path)` errors.

**Comment by jaakkor2** [comment]
This explains it
``` 
julia> stat(raw"C:\Users\jaakkor2\.julia\packages\PPTX\Otx2Q\templates\no-slides\[Content_Types].xml")
StatStruct for "C:\\Users\\jaakkor2\\.julia\\packages\\PPTX\\Otx2Q\\templates\\no-slides\\[Content_Types].xml"
   size: 3381 bytes
 device: 1745288286
  inode: 1062809
   mode: 0o100444 (-r--r--r--)
  nlink: 1
    uid: 0
    gid: 0
   rdev: 0
  blksz: 4096
 blocks: 8
  mtime:  (27 seconds ago)
  ctime:  (27 seconds ago)

julia> stat(raw"C:\Users\jaakkor2\.julia\dev\PPTX\templates\no-slides\[Content_Types].xml")
StatStruct for "C:\\Users\\jaakkor2\\.julia\\dev\\PPTX\\templates\\no-slides\\[Content_Types].xml"
   size: 3382 bytes
 device: 1745288286
  inode: 1061286
   mode: 0o100666 (-rw-rw-rw-)
  nlink: 1
    uid: 0
    gid: 0
   rdev: 0
  blksz: 4096
 blocks: 8
  mtime:  (12 minutes ago)
  ctime:  (12 minutes ago)

```
indeed, files in `../packages/PPTX/..` are read-only, while files in `../dev/PPTX/..` are read-write.  We copy the file to temp dir with those permissions.  This is why devved package worked.

**Comment by matthijscox-asml** [comment]
Excellent analysis!

Could we add one unit test for this in the CI? We could copy a template file to a tempdir and set it to read-only, then use that template. 

I really don't want to risk failing registered package versions again

**Comment by jaakkor2** [comment]
> I really don't want to risk failing registered package versions again

I understand the concern.  Sorry for the trouble I have caused.

I was able to test the changes locally with `]add C:\..localrepopath..\PPTX#debug`. So I am quite confident it should work now.

Best would be to have it in CI, since easily further development can make the same mistake.

**Comment by matthijscox-asml** [comment]
Confirmed the error by using `chmod(edited_template_path, 0o444; recursive=true)` inside the CI. I will make this the default test case.

**Comment by hellemo** [comment]
I haven't looked into the code, but could the temporary file be created in a temporary directory rather than in the package directory? E.g. using `mktempdir' to avoid editing files within the package directory.

**Comment by matthijscox-asml** [comment]
Yeah we always make a temporary directory, then copy the template into that, and do any editing there.

**Comment by hellemo** [comment]
Righ, I see, the issue is the permissions on the files you copy there. Sorry about the noise.
