### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by DanDeepPhase** [ASML-Labs/PPTX.jl#61]
Is there a way to set font size in a testbox or table?

**Comment by matthijscox-asml** [comment]
Ah I have quickly added the option for fontsize styling in the TextBox: https://github.com/ASML-Labs/PPTX.jl/pull/62
For tables I don't yet have a good way to configure the styling

**Comment by DanDeepPhase** [comment]
Thanks, that's a nice improvement
